- greenkeeper.json
Use 4-space tabs and add missing package.json reference
> chore: fix greenkeeper.json

- README.md
- package.json
- packages/d2/package.json
- packages/d2/src/index.js
- yarn.lock
This removes d2-packages as a cmd module from the main cli.
Some apps still rely on it, but they can use `d2-packages` directly.
> chore: remove packages as a cmd module

- .travis.yml
- package.json
- packages/d2-app/src/commands/scripts/release.js
So, I found that I can set the `pkgRoot` to the [@semantic-release/npm plugin](https://github.com/semantic-release/npm#options), so why not just run the plugin for each package in the `packages` directory?
BEHOLD!
> fix: publish multiple packages from inside a package

- .editorconfig
- .travis.yml
- packages/d2-app/src/commands/scripts/release.js
- packages/d2-app/src/commands/scripts/support/getWorkspacePackages.js
- packages/d2-app/src/commands/scripts/support/normalizeAndValidatePackages.js
- packages/d2-app/src/commands/scripts/support/semantic-release-update-deps.js
So... I may have gone a little overboard but I think this gets us all the way there. 
This looks through glob patterns in the `workspaces` property of the root `package.json`.  It then loops through all the package.jsons it can find and updates local dependencies (other packages found in the workspace) to `nextRelease.version` (using a `^` range).  It also updates the `version` property in each package.json, including the root.
~Right now this will try to publish the root package as well, which should fail because it's private.  We might want to filter out private repos before trying to publish them (or at least omit the root one in this specific case).~ = **done**
Also - I don't think we're actually updating the `yarn.lock` files anywhere, but this should find and push them all in the …
> feat: semantic release update deps

- packages/d2-app/src/commands/scripts/release.js
- packages/d2-app/src/commands/scripts/support/semantic-release-update-deps.js
Pass `NPM_CONFIG_ALLOW_SAME_VERSION` to `npm publish` so it doesn't fail when we've already updated the package.json version in the updateDeps plugin.
> fix: don't update the package.json version before npm stage

- packages/d2-app/src/commands/scripts/support/semantic-release-update-deps.js
This is a non-functional change to keep `package.json` files from bouncing back and forth between 2 and 4-space tabs when updated manually (using cli-style settings) and automatically.
> chore: update tab spacing when updating package.json

- greenkeeper.json
- package.json
- packages/app/package.json
- packages/cluster/README.md
- packages/cluster/package.json
- packages/create-app/package.json
- packages/create/package.json
- packages/create/templates/cli/package.json
- packages/main/package.json
- packages/utils/package.json
- yarn.lock
BREAKING CHANGE: cut major version 1.0.0
This upgrades to `cli-helpers-engine@^1.0.0` and `cli-style@^3.0.0`
> feat: upgrade cli-helpers-engine and cli-style dependencies

- packages/cluster/src/db.js
This fixes a silly typo which caused the command `d2 cluster up <version> --seed --seedFile <dbFile>` to fail with an undeclared variable exception.  Bummed we didn't catch it before 1.0, but 1.0.1 pre-announcement should be ok.
The earlier `dbFile =` hid this bug when the database was downloaded, rather than local, because `dbFile` was I guess implicitly defined by the assignment?  I didn't even know you could do that...
> fix: seed from file variable name was misspelled

- .travis.yml
- package.json
- packages/cluster/src/commands/down.js
- packages/cluster/src/commands/logs.js
- packages/cluster/src/commands/restart.js
- packages/cluster/src/commands/seed.js
- packages/cluster/src/commands/up.js
- packages/cluster/src/common.js
- packages/cluster/src/defaults.js
- packages/cluster/src/index.js
- packages/cluster/tests/setup-environment.js
- packages/cluster/tests/substitute-string-keys.js
- yarn.lock
Started with the `makeDockerImage` resolutions for supporting channels and versions from https://hub.docker.com/u/dhis2.
- Adds support for official dhis2 docker images in different channels (`core`, `core-dev`, `core-canary`)
- Adds `--db-version <string>`
- Adds `--variant <array>` 
- Adds `--channel <string>`
- Adds tests for configuration merging and generating docker image names
```bash
d2 cluster up 2.32 \
--channel canary
d2 cluster up custom \
--image amcgee/dhis2-core:dev-alpine \
--db-version 2.32 \ 
--seed
d2 cluster up stable \
--dhis2-version 2.31.4 \
--db-version 2.30 \
--seed
d2 cluster up 232-dev \
--channel dev \
--dhis2-version 2.32 \
--seed
```
To allow for subsequent startups without all the switches we need a mechanism (e.g. https://github.com/dhis2/cli/pull/53) to …
> feat: support official docker images

- packages/app/bin/d2-app
- packages/cluster/bin/d2-cluster
- packages/create-app/bin/d2-create-app
- packages/create/bin/d2-create
- packages/create/templates/cli/bin/{{executable}}
- packages/main/bin/d2
- packages/utils/bin/d2-utils
Stand-alone PR for avoiding double parsing of arguments with yargs leading to some strange bugs.
> fix: avoid double parsing of arguments

- packages/cluster/src/commands/down.js
- packages/cluster/src/commands/logs.js
- packages/cluster/src/commands/restart.js
- packages/cluster/src/commands/seed.js
- packages/cluster/src/commands/up.js
- packages/cluster/src/common.js
- packages/cluster/src/defaults.js
I forked https://github.com/amcgee/dhis2-backend to https://github.com/dhis2/docker-compose as I figure it's time for the Docker Compose setup to be under the official org on GitHub.
This PR updates the configuration default to the DHIS2 docker-compose repo.
> fix: use dhis2/docker-compose instead of amcgee/dhis2-backend as default

- packages/cluster/src/commands/compose.js
- packages/cluster/src/commands/db.js
- packages/cluster/src/commands/db_cmds/backup.js
- packages/cluster/src/commands/db_cmds/restore.js
- packages/cluster/src/commands/logs.js
- packages/cluster/src/commands/up.js
- packages/cluster/src/helpers/db/backup.js
- packages/cluster/src/helpers/db/index.js
- packages/cluster/src/helpers/db/restore.js
- packages/utils/package.json
- yarn.lock
This feature PR adds a few handy commands to the `cluster` namespace:
1) It adds `d2 cluster db backup <name> <path>` and `d2 cluster db restore <name> [path]` for easy database lifecycle management outside the cluster volumes.
2) It adds the `d2 cluster compose <name> -- [args...]` command which passes through to the underlying `docker-compose` and allows the user to perform arbitrary `docker-compose` commands without needing to specify the compose project name or the location of the docker-compose.yml file (which is in the d2 cache).  An example usage is `d2 cluster compose dev -- exec db 'sh'` which will execute an interactive shell terminal in the `db` container.
3) It enhances the `d2 cluster up` command by automatically pulling the latest docker images when `--update` is specified …
> feat: add cluster db commands, update images on up, add compose cmd

- packages/app/package.json
- packages/cluster/package.json
- packages/cluster/src/commands/list.js
- packages/cluster/src/common.js
- packages/create-app/package.json
- packages/create/package.json
- packages/create/templates/cli/package.json
- packages/main/package.json
- packages/utils/package.json
- yarn.lock
This adds the command `d2 cluster list` which displays a list of the configured clusters and their current status, i.e.
It also upgrades the dependency on `@dhis2/cli-helpers-engine` which fixes a bug in the Cache implementation and adds support for capturing the output of `exec` commands.
> feat: add `cluster list` command

- packages/cluster/src/commands/list.js
Fixes a minor bug where `Up about a minute` didn't match the `Up \d+` regex.  Also passes `-a` to `docker ps` so that we can also see stopped containers, and adds a status check for `Exited`
> fix: improve cluster list formatting

- packages/cluster/src/common.js
This is a simple fix so that we can properly detect running containers from previously-started clusters.  Docker-compose does some normalization of the project name we pass it before naming the containers it starts.
Fixes bugs in `d2 cluster list` and `d2 cluster status`
> fix: correctly normalize compose project name

- packages/utils/src/cmds/release.js
This can cause [release failures to silently succeed](https://travis-ci.com/dhis2/app-platform/builds/126588761#L472), which is bad news in CI deployment 
I'm also worried that the git portion of semantic-release [succeeded](https://github.com/dhis2/app-platform/commit/bef5557c48e6fc429c41a44ff288fb7afa45440f) in pushing the version commit, even though the preceding npm publish step failed!  That is not covered in this fix.
> fix: don't swallow release command errors

- packages/cluster/src/common.js
See title. Not much to say.
Had one student who thought something had gone wrong when they saw the error.
> chore: list doesn't output ugly error if cache folder doesn't exist

- packages/utils/src/cmds/release.js
Adds check if nextRelease and lastRelease are truthy before picking
props from them.
In some situations when running semantic-release we get a result back
that has `nextRelease` as undefined. We naively read from that object
and wind up with a "cannot read property from undefined" error that
makes the process exit with code 1, marking it as failed in CI.
Technically this may be a bug in semantic-release, as their docs state
that the result obj should be false or complete[1].
And example for how this looks in CI is attached[2].
[1] https://github.com/semantic-release/semantic-release/blob/master/docs/developer-guide/js-api.md#result
[2] https://github.com/dhis2/app-hub/runs/554982530#step:9:109
> fix(release): avoid picking a prop from undefined

- packages/cluster/src/common.js
- packages/cluster/tests/setup-environment.js
This caused the below error on a fresh cluster with default config:
```sh
> d2 cluster up master --verbose
[DEBUG] Resolved configuration
{ dhis2Version: 'master',
dbVersion: 'dev',
channel: 'dev',
image: 'dhis2/core{channel}:{version}',
port: 8080,
customContext: false,
update: false,
seed: false,
dockerComposeDirectory: 'cluster',
dockerComposeRepository: 'https://github.com/dhis2/docker-compose/archive/master.tar.gz',
demoDatabaseURL: 'https://github.com/dhis2/dhis2-demo-db/blob/master/sierra-leone/{version}/dhis2-db-sierra-leone.sql.gz?raw=true',
_: [ 'cluster', 'up' ],
verbose: true,
cache: '/Users/awm/.cache/d2',
'$0': '/usr/local/bin/d2',
name: 'master',
getCache: [Function],
contextPath: '',
dockerImage: 'dhis2/core-dev:master' }
[DEBUG] Skipping docker compose repo …
```
> fix: don't set DHIS2_CORE_CONFIG to undefined, it needs to be unset

- packages/cluster/package.json
- packages/main/package.json
- yarn.lock
Closes #315 
The `cluster` package is [using `cli-table3`](https://github.com/dhis2/cli/blob/d404134ac71c138afd9a89b418978be5e55d3e77/packages/cluster/src/commands/list.js#L3), but that dependency was only declared for the main `d2` package (`@dhis2/cli`).  When installed and run independently (`npx @dhis2/cli-cluster --help`, not recommended but exhibiting this issue) the `cluster` command can't resolve the `cli-table3` dependency because it is only installed with the full CLI.  `yarn global add @dhis2/cli && d2 cluster --help` worked, but we should be explicit in our dependency declarations.
The following error is caused by this missing dependency:
```bash
➜ npx @dhis2/cli-cluster --help
npx: installed 190 in 13.261s
Cannot find module 'cli-table3'
Require stack:
- …
```
> fix: add cli-table3 as d2-cluster dependency

- packages/cluster/src/defaults.js
Closes #317 - DHIS2 Sierra Leone demo databases are no longer hosted primarily on GitHub, so update the default url for seed database download to point to the new location.
> fix: use new location for sample database downloads

- packages/utils/src/cmds/release.js
When not releasing to NPM in a standard repo (as opposed to a monorepo),
no logic to update the package.json version field was triggered.
This change runs the semantic-release/npm[1] plugin with "npmPublish"
disabled. This updates the package.json version field without publishing
to NPM.
In normal operation we do want to trigger the release, so if the
publisher is set to 'npm' it works according to the default.
[1] https://github.com/semantic-release/npm#options
> fix(release): always update package.json version

- docs/commands/d2-cluster.md
Actual folder is 'clusters', however docs all reference the 'cluster' folder.
> docs: correct name of clusters directory

- packages/app/package.json
- packages/app/src/index.js
- packages/cluster/package.json
- packages/create-app/package.json
- packages/create/package.json
- packages/create/templates/cli/package.json
- packages/main/package.json
- packages/main/src/index.js
- packages/utils/package.json
- packages/utils/src/index.js
- yarn.lock
Increases the utility of the global d2 tool for developers by preferring
the version of the CLI tool that is installed over the globally bundled
one.
Before this change these two commands run in the same project can yield
different results:
d2 style check          # global
yarn d2-style check     # local
After the change, they will both use the local version:
d2 style check          # local
yarn d2-style check     # local
Jira-ticket-key: CLI-68
Jira-ticket-URL: https://jira.dhis2.org/browse/CLI-68
Depends on:
- https://github.com/dhis2/cli-helpers-engine/pull/143
> feat(cli): prefer project-local tools

- packages/main/package.json
- yarn.lock
Bump `@dhis2/cli-helpers-engine` to v3.2.1, which [includes a fix for `createModuleLoader` that is required when `@dhis2/cli` is used as global package](https://github.com/dhis2/cli-helpers-engine/pull/151).
> fix(main): bump cli-helpers-engine to fix undefined project root issue

- packages/app/package.json
- packages/cluster/package.json
- packages/create-app/package.json
- packages/create/package.json
- packages/create/templates/cli/package.json
- packages/utils/package.json
- yarn.lock
Bump `@dhis2/cli-helpers-engine` for all packages under the `cli` workspace. Prevents issues where a global install of `@dhis2/cli` is upgraded to benefit from the project root handling fix while subpackages such as `@dhis2/cli-app` do not.
> fix: bump cli-helpers-engine for all packages

- .github/workflows/rebuild-docs.yml
Todo:
Links:
- https://app.netlify.com/sites/dhis2-developer-portal/overview
- https://github.com/dhis2/developer-portal/
- https://docs.netlify.com/configure-builds/build-hooks/
- https://github.com/dhis2/developer-portal/blob/main/docs-migrate.js
- https://github.com/orgs/community/discussions/27027
- https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore
> ci: ping netlify to rebuild on change

- packages/main/package.json
Trying this to get the right package dependencies for npm: cli-app-scripts, app-runtime, and react
https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides
> fix(deps): test overrides

- .github/workflows/dhis2-deploy-netlify.yml
- .github/workflows/dhis2-verify-node.yml
- packages/app/package.json
- yarn.lock
Fixes [LIBS-578](https://dhis2.atlassian.net/browse/LIBS-587)
Fixes peer dependency conflicts that were causing infinite loops when using`npm` v7+ to install the d2 cli. Can be tested using the latest `alpha` version of `@dhis2/cli`:
```sh
npm i -g @dhis2/cli
```
---
~**Note:** this constitutes a breaking change, since the minimum Node version will now be 16~
**Update:** _this_ change did not introduce the Node 14 incompatibility; it was actually present previously with `cli-app-scripts`. For that reason... I think a major version bump isn't necessary, but it's a bit awkward that a breaking change has happened outside of our control.
**A quick summary:** When running `d2 app scripts init` on Node 14, this error breaks the installation:
```
error workbox-webpack-plugin@6.6.1: The engine …
```
> fix(deps): upgrade @dhis2/cli-app-scripts for peer deps fixes [LIBS-578]
